# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
#       name:
#         description: 'Provide unique name'
#         required: true
      command:
        description: 'Command to execute'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ucli"
  ucli:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    env:
      name: default

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: get unique job-name
          run: |
            name=$(curl https://random.justyy.workers.dev/api/random/?n=12)
            ${{ env.NAME = name }}
            
        - name: run user provided command
          run: ${{ github.event.inputs.command }} > log.txt

        - uses: actions/upload-artifact@v2
          with:
            name: ${{ github.event.inputs.name }}
            path: log.txt
            retention-days: 1
