# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
#     inputs:
#       js-package:
#         description: 'Package to install from npm'
#         required: true
#         # default: 'Mona the Octocat'
      command:
        description: 'Command to execute'
        required: true
        # default: 'The Octoverse'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ucli:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Install Dependencies
#         run: npm install
        
#       - name: Install JavaScript library
#         run: npm install ${{ github.event.inputs.js-package }}
        
#       - name: Run installed library
#         run: npx ${{ github.event.inputs.command }}

#         - run: mkdir -p output

        - name: test-run
          run: ${{ github.event.command }} > log.txt

        - uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: log.txt

#         - name: test-run
#           run: corona-cli

#       - name: Run a multi-line script
#         run: |
#           echo "Hi ${{ github.event.inputs.name }}!"
#           echo "You're in ${{ github.event.inputs.home }}."
